; HMI — ESP32-32E con pantalla 3.2" (sólo interfaz)
; Cargar:  pio run -t upload      Monitor:  pio device monitor
[env:hmi]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv  ; LVGL y sus fuentes necesitan más de 1,3 MB
build_flags = -I ../compartido -I include -D LV_CONF_INCLUDE_SIMPLE
lib_deps =
  lvgl/lvgl@9.2.2             ; interfaz gráfica
  lovyan03/LovyanGFX@1.1.16   ; pantalla ST7789 y táctil XPT2046
