; Control — ESP32 DevKit V1 (sólo control)
; Cargar:  pio run -t upload      Monitor:  pio device monitor
[env:control]
platform = espressif32@7.0.1
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_flags = -I ../compartido -Wall
lib_deps =
  sensirion/Sensirion Gas Index Algorithm@3.2.3  ; índice de olor a partir del SGP40
